### ISSUE TITLE
Apply to Batch

### ISSUE THREAD

**Issue by acobb83** [Engineero/tf_sprinkles#5]
Is there anyway to apply this function to a batched Tensorflow dataset of images? So it can be called during model.fit?

**Comment by Engineero** [comment]
Good question. I will look into it. Have you tried it? Can you give me a minimal example of what you're looking at and what the result/errors are?

**Comment by acobb83** [comment]
I'd want to use it in the following scenario for pre-processing images in a Tensor batch.

```
train_labelsC = to_categorical(y_train)
valid_labelsC = to_categorical(y_val)
test_labelsC = to_categorical(y_test)

tf_trnImg = tf.convert_to_tensor(x_train)
tf_valImg = tf.convert_to_tensor(x_val)
tf_tstImg = tf.convert_to_tensor(x_test)

trn_dataset212 = tf.data.Dataset.from_tensor_slices((tf_trnImg,train_labelsC)) 
vld_dataset212 = tf.data.Dataset.from_tensor_slices((tf_valImg,valid_labelsC)) 
tst_dataset212 = tf.data.Dataset.from_tensor_slices((tf_tstImg ,test_labelsC))

sprinkles = Sprinkles(num_holes=1, side_length=8)

def pre_process_image(image, label):

  image = tf.image.random_brightness(image, 0.05)
  image = tf.image.random_contrast(image, 0.4,0.6)

  rdmSz = random.randint(25, 28)
  image = tf.image.random_crop(image, size=[rdmSz, rdmSz, 3] )#, seed=None, name=None)

  image = tf.image.random_flip_left_right(image)
  image = tf.image.random_flip_up_down(image)
  image = tf.image.resize_with_pad(image,32,32)
  image = sprinkles(image)

  print("a")

  return image, label

TRAIN_BATCH_SIZE = 8
train_batches212 = trn_dataset212.cache().map(pre_process_image, num_parallel_calls=AUTOTUNE).batch(TRAIN_BATCH_SIZE).repeat().prefetch(AUTOTUNE).shuffle(int(TRAIN_BATCH_SIZE)*4) #pre_process_image
validation_batches212 = vld_dataset212.cache().map(pre_process_image, num_parallel_calls=AUTOTUNE).batch(TRAIN_BATCH_SIZE).repeat().prefetch(AUTOTUNE).shuffle(int(TRAIN_BATCH_SIZE)*4)
test_batches212 = tst_dataset212.cache().map(pre_process_image, num_parallel_calls=AUTOTUNE).batch(TRAIN_BATCH_SIZE).repeat().prefetch(AUTOTUNE).shuffle(int(TRAIN_BATCH_SIZE)*4)

```

**Comment by Engineero** [comment]
Does this produce an error? If so, can you copy the full traceback into here? Otherwise what are you seeing that isn't want you expect to see?

I might have time to work on this over the weekend, but with `tf.Dataset` it might be a bit of a project to reproduce. Having any error trace you see may help speed things up.

**Comment by Engineero** [comment]
Just bumping my traceback request. Please copy any and all error text you see so I can narrow down what's going on.

**Comment by acobb83** [comment]
Did you change something? Because when I run it now it is working.

**Comment by Engineero** [comment]
I didn't change anything, but I'm glad to hear that it's working now. I'm going to close for now, but if you are able to reproduce the error, please reopen and copy the full traceback into here so I can try to track it down. Cheers!
